### ISSUE TITLE
Add --underscored option to model:create

### ISSUE THREAD

**Issue by theRemix** [sequelize/cli#120]
by default, migrations generated from `sequelize model:create` generate camel cased timestamp fields.  

````
createdAt:
  allowNull: false
  type: DataTypes.DATE
updatedAt:
  allowNull: false
  type: DataTypes.DATE
````

add `--underscore` option to `sequelize model:create` to generate underscored column names.

````
created_at:
  allowNull: false
  type: DataTypes.DATE
updated_at:
  allowNull: false
  type: DataTypes.DATE
````
